# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 18:27
from __future__ import unicode_literals

import apps.url.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('desktop', 'Desktop'), ('tablet', 'Tablet'), ('mobile', 'Mobile')], max_length=10)),
                ('target', models.URLField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=apps.url.utils.random_hash_generator, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('target', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='deviceurl',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_urls', to='url.ShortUrl'),
        ),
        migrations.AlterUniqueTogether(
            name='deviceurl',
            unique_together=set([('type', 'url')]),
        ),
    ]
