# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceurl',
            old_name='count',
            new_name='counter',
        ),
        migrations.AddField(
            model_name='shorturl',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
