# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_auto_20170129_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='target',
        ),
        migrations.AddField(
            model_name='shorturl',
            name='url',
            field=models.URLField(default='', unique=True),
            preserve_default=False,
        ),
    ]
