# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 00:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0003_auto_20170130_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='url',
            new_name='target',
        ),
    ]
