# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 14:52
from __future__ import unicode_literals

import apps.url.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0004_auto_20170130_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='hash',
            field=models.CharField(default=apps.url.utils.random_hash_generator, editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
